// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SWP_SchoolMedicalManagementSystem_BussinessOject.Context;

#nullable disable

namespace SWP_SchoolMedicalManagementSystem_BussinessOject.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250612095258_Update healthRecord properties")]
    partial class UpdatehealthRecordproperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthCheckupCampaignUser", b =>
                {
                    b.Property<Guid>("HealthCheckupCampaignsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicalStaffsId")
                        .HasColumnType("uuid");

                    b.HasKey("HealthCheckupCampaignsId", "MedicalStaffsId");

                    b.HasIndex("MedicalStaffsId");

                    b.ToTable("HealthCheckupCampaignUser");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<List<string>>("Images")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthCheckupCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CampaignName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HealthCheckupCampaigns");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthCheckupConsentForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConsentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConsentStatus")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("HealthCheckupCampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonForDecline")
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckupCampaignId");

                    b.HasIndex("StudentId");

                    b.ToTable("HealthCheckupConsentForms");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthCheckupResults", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbnormalSigns")
                        .HasColumnType("text");

                    b.Property<float?>("BloodPressureDia")
                        .HasColumnType("real");

                    b.Property<float?>("BloodPressureSys")
                        .HasColumnType("real");

                    b.Property<DateTime>("CheckupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DentalCheckupResult")
                        .HasColumnType("text");

                    b.Property<Guid?>("HealthCheckupScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("HearingLeftResult")
                        .HasColumnType("text");

                    b.Property<string>("HearingRightResult")
                        .HasColumnType("text");

                    b.Property<float?>("HeartRate")
                        .HasColumnType("real");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<string>("OtherResults")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ParentResultNotificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ParentResultNotified")
                        .HasColumnType("boolean");

                    b.Property<string>("Recommendations")
                        .HasColumnType("text");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VisionLeftResult")
                        .HasColumnType("text");

                    b.Property<string>("VisionRightResult")
                        .HasColumnType("text");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckupScheduleId");

                    b.ToTable("HealthCheckupResults");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<string>("BloodType")
                        .HasColumnType("text");

                    b.Property<string>("ChronicDiseases")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("HearingLeft")
                        .HasColumnType("text");

                    b.Property<string>("HearingRight")
                        .HasColumnType("text");

                    b.Property<string>("Height")
                        .HasColumnType("text");

                    b.Property<string>("OtherNotes")
                        .HasColumnType("text");

                    b.Property<string>("PastMedicalHistory")
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VaccinationHistory")
                        .HasColumnType("text");

                    b.Property<string>("VisionLeft")
                        .HasColumnType("text");

                    b.Property<string>("VisionRight")
                        .HasColumnType("text");

                    b.Property<string>("Weight")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicalConsultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsultationNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("MedicalStaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicalStaffId");

                    b.HasIndex("ResultId");

                    b.HasIndex("StudentId");

                    b.ToTable("MedicalConsultations");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicalIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionsTaken")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IncidentType")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<DateTime>("ParentNotificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ParentNotified")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("MedicalIncidents");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicalSupplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<List<string>>("Image")
                        .HasColumnType("text[]");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Supplier")
                        .HasColumnType("text");

                    b.Property<string>("SupplyName")
                        .HasColumnType("text");

                    b.Property<int>("SupplyType")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedicalSuppliers");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicalSupplyUsage", b =>
                {
                    b.Property<Guid>("SupplyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UsageDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SupplyId", "IncidentId");

                    b.HasIndex("IncidentId");

                    b.ToTable("MedicalSupplyUsages");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicationRequests", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Dosage")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<Guid>("MedicalStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("MedicalStaffNotes")
                        .HasColumnType("text");

                    b.Property<string>("MedicationName")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicalStaffId");

                    b.HasIndex("StudentId");

                    b.ToTable("MedicationRequests");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicineDiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("MedicineDiaries");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("text");

                    b.Property<string>("StudentCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.StudentHealthCheckupSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("HealthCheckupCampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckupCampaignId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentHealthCheckupSchedules");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.StudentVaccinationSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("VaccinationCampaignId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("VaccinationCampaignId");

                    b.ToTable("StudentVaccinationSchedules");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.VaccinationCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CampaignName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VaccineType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VaccinationCampaigns");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.VaccinationConsentForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConsentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConsentStatus")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ReasonForDecline")
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("VaccinationCampaignId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("VaccinationCampaignId");

                    b.ToTable("VaccinationConsentForms");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.VaccinationResults", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DosageGiven")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("SideEffects")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("VaccinationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VaccinationScheduleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VaccinationScheduleId");

                    b.ToTable("VaccinationResults");
                });

            modelBuilder.Entity("UserVaccinationCampaign", b =>
                {
                    b.Property<Guid>("MedicalStaffsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaccinationCampaignsId")
                        .HasColumnType("uuid");

                    b.HasKey("MedicalStaffsId", "VaccinationCampaignsId");

                    b.HasIndex("VaccinationCampaignsId");

                    b.ToTable("UserVaccinationCampaign");
                });

            modelBuilder.Entity("HealthCheckupCampaignUser", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthCheckupCampaign", null)
                        .WithMany()
                        .HasForeignKey("HealthCheckupCampaignsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("MedicalStaffsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Blog", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.User", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthCheckupConsentForm", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthCheckupCampaign", "HealthCheckupCampaign")
                        .WithMany()
                        .HasForeignKey("HealthCheckupCampaignId");

                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Student", "Student")
                        .WithMany("CheckupConsentForms")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HealthCheckupCampaign");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthCheckupResults", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.StudentHealthCheckupSchedule", "HealthCheckupSchedule")
                        .WithMany()
                        .HasForeignKey("HealthCheckupScheduleId");

                    b.Navigation("HealthCheckupSchedule");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthRecord", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Student", "Student")
                        .WithOne("HealthRecord")
                        .HasForeignKey("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthRecord", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicalConsultation", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.User", "MedicalStaff")
                        .WithMany("MedicalConsultations")
                        .HasForeignKey("MedicalStaffId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthCheckupResults", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Student", "Student")
                        .WithMany("MedicalConsultations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MedicalStaff");

                    b.Navigation("Result");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicalIncident", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Student", "Student")
                        .WithMany("MedicalIncidents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicalSupplyUsage", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicalIncident", "Incident")
                        .WithMany("MedicalSupplyUsages")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicalSupplier", "MedicalSupply")
                        .WithMany("MedicalSupplyUsages")
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("MedicalSupply");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicationRequests", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.User", "MedicalStaff")
                        .WithMany("MedicationRequests")
                        .HasForeignKey("MedicalStaffId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Student", "Student")
                        .WithMany("MedicationRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MedicalStaff");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicineDiary", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Student", "Student")
                        .WithMany("MedicineDiaries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Student", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.User", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.StudentHealthCheckupSchedule", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthCheckupCampaign", "HealthCheckupCampaign")
                        .WithMany("Schedules")
                        .HasForeignKey("HealthCheckupCampaignId");

                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Student", "Student")
                        .WithMany("HealthCheckupSchedules")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HealthCheckupCampaign");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.StudentVaccinationSchedule", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Student", "Student")
                        .WithMany("VaccinationSchedules")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.VaccinationCampaign", "VaccinationCampaign")
                        .WithMany("Schedules")
                        .HasForeignKey("VaccinationCampaignId");

                    b.Navigation("Student");

                    b.Navigation("VaccinationCampaign");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.VaccinationConsentForm", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Student", "Student")
                        .WithMany("VaccinationConsentForms")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.VaccinationCampaign", "VaccinationCampaign")
                        .WithMany()
                        .HasForeignKey("VaccinationCampaignId");

                    b.Navigation("Student");

                    b.Navigation("VaccinationCampaign");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.VaccinationResults", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.StudentVaccinationSchedule", "VaccinationSchedule")
                        .WithMany()
                        .HasForeignKey("VaccinationScheduleId");

                    b.Navigation("VaccinationSchedule");
                });

            modelBuilder.Entity("UserVaccinationCampaign", b =>
                {
                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("MedicalStaffsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.VaccinationCampaign", null)
                        .WithMany()
                        .HasForeignKey("VaccinationCampaignsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.HealthCheckupCampaign", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicalIncident", b =>
                {
                    b.Navigation("MedicalSupplyUsages");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.MedicalSupplier", b =>
                {
                    b.Navigation("MedicalSupplyUsages");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.Student", b =>
                {
                    b.Navigation("CheckupConsentForms");

                    b.Navigation("HealthCheckupSchedules");

                    b.Navigation("HealthRecord");

                    b.Navigation("MedicalConsultations");

                    b.Navigation("MedicalIncidents");

                    b.Navigation("MedicationRequests");

                    b.Navigation("MedicineDiaries");

                    b.Navigation("VaccinationConsentForms");

                    b.Navigation("VaccinationSchedules");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.User", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("MedicalConsultations");

                    b.Navigation("MedicationRequests");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SWP_SchoolMedicalManagementSystem_BussinessOject.Entity.VaccinationCampaign", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
